name: Automated Deployment to Development
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Authenticate with GCP
        env:
          GCP_AUTH_JSON: ${{ secrets.DEVELOPMENT_GCP_AUTH_JSON }}
        run: |
          echo "$GCP_AUTH_JSON" > gcp-auth.json
          gcloud auth activate-service-account --key-file=gcp-auth.json
          rm gcp-auth.json

      - name: Deploy to GCP VM Instance
        env:
          GCP_SSH_PRIVATE_KEY: ${{ secrets.DEVELOPMENT_GCP_SSH_PRIVATE_KEY }}
          GCP_USERNAME: ${{ secrets.DEVELOPMENT_GCP_USERNAME }}
          GCP_STATIC_IP: ${{ secrets.DEVELOPMENT_GCP_STATIC_IP }}
        run: |
          echo "$GCP_SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $GCP_USERNAME@$GCP_STATIC_IP "
          sudo su && cd /home/rifqi_farel/cirrhocheck-api && git pull origin main && 
          python3 -m pip install --upgrade pip && pip install -r requirements.txt && 
          python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"