name: Automated Deployment for Staging

on:
  push:
    branches:
      - staging
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Deploy to GCP VM Instance
        env:
          GCP_SSH_PRIVATE_KEY: ${{ secrets.DEVELOPMENT_GCP_SSH_PRIVATE_KEY }}
          GCP_USERNAME: ${{ secrets.DEVELOPMENT_GCP_USERNAME }}
          GCP_STATIC_IP: ${{ secrets.DEVELOPMENT_GCP_STATIC_IP }}
        run: |
          echo "$GCP_SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $GCP_USERNAME@$GCP_STATIC_IP "
          cd /home/rifqi_farel/cirrhocheck-api && git switch staging &&
          git pull origin staging && python3 -m pip install --upgrade pip && 
          python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt &&
          python3 manage.py migrate && sudo systemctl restart gunicorn"