jobs:
  test_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: Set up environment variables
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run tests with coverage
        run: |
          python manage.py migrate
          coverage run manage.py test -v 2
          coverage report
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov
